description: Inicialize aplicações web react preparadas para ambientes microfrontend com webpack module federation.

name: matter-web-react

displayName: Stack Web React

picture: "react.png"

category: Frontend

compatibility:
  - webpack 5
  - react 17

about: about.md

useCases:
  - title: APP React com deploy AWS
    content: useCase-deploy.md
    stackfile: stackfiles/deploy.yaml
  - title: Criar aplicação React Shell
    content: useCase-shell-microfrontend.md
    stackfile: stackfiles/shell-microfrontend.yaml
  - title: Criar aplicação React
    content: useCase.md
    stackfile: stackfiles/default.yaml
